### PR TITLE
Stylelint 13

### PR DESCRIPTION
**Pull request by limonte**
Support Stylelint 13: https://github.com/stylelint/stylelint/releases/tag/13.0.0

### CODE REVIEW

**Comment by silverwind** [comment]
Can we just make it `>=7.0.0`?

**Comment by limonte** [comment]
> Can we just make it `>=7.0.0`? It'd be less maintenance required if it is reasonable to expect compatibility.

It is unreasonable to expect compatibility in **major** releases. 

> MAJOR version when you make **incompatible API changes**

Read more about semver: https://semver.org/

**Comment by silverwind** [comment]
Thanks, I know about semver. Up to the maintainer of course. I'd personally trust stylelint to not have breaking API changes in their next major releases.

**Comment by limonte** [comment]
> I'd personally trust stylelint to not have breaking API changes in their next major releases.

Why would they release major releases without breaking API changes?

**Comment by silverwind** [comment]
I meant relevant breaking changes, but whatever I hope this gets merged soon.

**Pull request merged**
