### PR TITLE
Update stylelint peer dependency

### PR DESCRIPTION
**Pull request by rgant**
Latest version of stylelint is 15.2.0

### CODE REVIEW

**Comment by rgant** [comment]
I understand the idea of limiting the version range, but if this was my package I would just say
```
stylelint": ">=7.0.0"
```
Unless you are actively monitoring and testing peer dependency changes for compatibility the way that happens is to allow your users to be the QA and test the latest versions. With modern npm peerDependency resolutions it is difficult to install something newer than your range in the CI systems that run my automated tests which would let me know if there are problems.

**Review by limonte — APPROVED** [review]
FWIW I can confirm that the current version of. `stylelint-csstree-validator` works with Stylelint 15 on all of my projects

**Comment by limonte** [comment]
Good news!

You don't actually need `stylelint-csstree-validator` plugin anymore, there's a built-in rule in Stylelint 15: [`declaration-property-value-no-unknown`](https://stylelint.io/migration-guide/to-15/#added-declaration-property-value-no-unknown-rule)

Here's what I did for my projects: https://github.com/sweetalert2/stylelint-config/commit/b17a7f48ca2608360aabffacfd591988e5f3b1a9

**Comment by rgant** [comment]
Does that include SCSS/SASS support?

**Comment by limonte** [comment]
> Does that include SCSS/SASS support?

no

**Comment by rgant** [comment]
Seems like this one does so it is still useful
https://github.com/csstree/stylelint-validator/blob/c7fac4f85704fd740526f31ae6122c7d1edc7adb/lib/index.js#L18

**Comment by limonte** [comment]
> Seems like this one does so it is still useful
> 
> https://github.com/csstree/stylelint-validator/blob/c7fac4f85704fd740526f31ae6122c7d1edc7adb/lib/index.js#L18

You're right, I've updated my previous comment, thanks 👍

**Comment by rgant** [comment]
Any chance this can be merged soon? I am blocked in updating stylelint by this dependency.

**Comment by bryanjtc** [comment]
Any update on this?

**Comment by rgant** [comment]
I added this to my package.json to work around this apparently dead project.

```json
  "overrides": {
    "stylelint-csstree-validator@^2.1.0": {
      "stylelint@>=7.0.0 <15.0.0": "*"
    }
  }
```

**Comment by lahmatiy** [comment]
Very sorry in delay for an update. That's fixed in [v3.0.0](https://github.com/csstree/stylelint-validator/releases/tag/v3.0.0). The fix is also required to drop older versions of Node.js, that's why it's a major version bump due to semver.

**Pull request closed without merging**
